# To bump cache:
# Increment & Replace: 'CACHE_V1' in this config

version: 2.1
jobs:
  build:
    working_directory: ~/convus/convus-browser-extension
    parallelism: 2
    shell: /bin/bash --login
    environment:
      NODE_ENV: test
    docker:
      - image: cimg/node:18.14.2
    steps:
      - checkout
      - restore_cache:
          keys:
            # This branch if available
            - CACHE_V1-dep-{{ .Branch }}-
            # Default branch if not
            - CACHE_V1-dep-main-
            # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
            - CACHE_V1-dep-
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: install system libraries
          command: sudo apt-get update
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: CACHE_V1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.cache/yarn
            - ~/.cache/bundle
      - run:
          name: JS lint check
          command: yarn standard
      - run:
          name: "Jest: Tests"
          command: |
            mkdir -p test-results/junit
            yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "test-results/junit/"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-artifacts
workflows:
  version: 2
  commit:
    jobs:
      - build
